name: SBOM Processing & Dependency-Track Report Download

on:
  push:

jobs:
  sbom-analysis:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Make Script Executable
        run: chmod +x scripts/sbom_pipeline.sh

      - name: Run SBOM Processing Pipeline
        run: ./scripts/sbom_pipeline.sh
        env:
          DEP_TRACK_URL: ${{ secrets.DEP_TRACK_URL }}
          DEP_TRACK_API_KEY: ${{ secrets.DEP_TRACK_API_KEY }}
