name: SBOM Upload to Dependency Track (Self-Hosted)

on:
  push:
    paths:
      - "security-audit/*.json"  # Trigger only when SBOMs are added/updated
  workflow_dispatch:  # Allows manual trigger

jobs:
  upload_sbom:
    runs-on: self-hosted  # Runs on your self-hosted runner
    steps:
      - name: Checkout Repository  # Ensures scripts/ folder exists
        uses: actions/checkout@v3

      - name: Verify Script Existence
        run: |
          if [ ! -f scripts/sbom_pipeline.sh ]; then
            echo "ERROR: Script 'scripts/sbom_pipeline.sh' not found!"
            exit 1
          fi

      - name: Make Shell Script Executable
        run: chmod +x scripts/sbom_pipeline.sh

      - name: Run SBOM Upload Script
        env:
          DT_API_KEY: ${{ secrets.DT_API_KEY }}
        run: scripts/sbom_pipeline.sh

