name: SBOM Upload to Dependency Track (Self-Hosted)

on:
  push:
    paths:
      - "security-audit/*.json"  # Trigger only when SBOMs are added/updated
  workflow_dispatch:  # Allows manual trigger

jobs:
  upload_sbom:
    runs-on: self-hosted  # Executes on your self-hosted runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Make Shell Script Executable
        run: chmod +x scripts/dependency_track_upload.sh

      - name: Run SBOM Upload Script
        env:
          DT_API_KEY: ${{ secrets.DT_API_KEY }}
        run: scripts/dependency_track_upload.sh
