name: Generate SBOM with Docker

on:
  push:
    branches:
      - main  # Adjust the branch as needed
  pull_request:
    branches:
      - main  # Adjust the branch as needed

jobs:
  generate-sbom:
    runs-on: self-hosted  # Use self-hosted runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for security-audit folder
        id: check-folder
        run: |
          if [ -d "security-audit" ]; then
            echo "security-audit folder exists"
            echo "folder_exists=true" >> $GITHUB_OUTPUT
          else
            echo "security-audit folder does not exist, creating it"
            mkdir security-audit
            echo "folder_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate SBOM using Docker
        run: |
          # Get repository name
          REPO_NAME=$(basename $(git rev-parse --show-toplevel))

          # Count existing BOM files in security-audit folder
          BOM_COUNT=$(ls -1q security-audit/$REPO_NAME-*.xml 2>/dev/null | wc -l)
          BOM_COUNT=$((BOM_COUNT + 1))

          # Generate SBOM file with the specified naming convention using Docker
          docker run --rm -v $(pwd):/app cyclonedx/cyclonedx-cli cyclonedx-bom -o /app/security-audit/$REPO_NAME-$BOM_COUNT.xml

      - name: Commit and push SBOM file (if folder was created)
        if: steps.check-folder.outputs.folder_exists == 'false'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add security-audit
          git commit -m "chore: Add security-audit folder and initial SBOM"
          git push
