name: Generate CycloneDX SBOM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: self-hosted  # Use your self-hosted runner

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Ensure this matches your project's Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Install CycloneDX NPM Tool
        run: npm install --save-dev @cyclonedx/cyclonedx-npm

      - name: Generate SBOM
        run: |
          mkdir -p security-audit
          npx @cyclonedx/cyclonedx-npm --output-file security-audit/bom.json
