name: Generate SBOM with Snyk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Snyk CLI
        run: |
          curl -Lo snyk https://github.com/snyk/snyk/releases/latest/download/snyk-linux
          chmod +x snyk
          sudo mv snyk /usr/local/bin/

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Ensure security-audit Directory Exists
        run: mkdir -p security-audit

      - name: Generate SBOM
        run: |
          REPO_NAME=$(basename $GITHUB_REPOSITORY)
          TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
          SBOM_FILE="security-audit/${REPO_NAME}_SBOM_${TIMESTAMP}.json"
          snyk sbom --format cyclonedx1.4+json > "$SBOM_FILE"

      - name: Commit and Push SBOM to Repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add security-audit/
          git commit -m "Updated SBOM"
          git push
        continue-on-error: true  # Avoids errors if no changes exist
